"""url for category

Revision ID: 1a4145135529
Revises: 499b785652a1
Create Date: 2015-01-28 00:58:50.625449

"""

# revision identifiers, used by Alembic.
revision = '1a4145135529'
down_revision = '499b785652a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('url', sa.String(length=120), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'url')
    ### end Alembic commands ###
