"""Node models

Revision ID: 1a7a18e7a5ad
Revises: 28e080284d0c
Create Date: 2015-04-07 01:25:33.594036

"""

# revision identifiers, used by Alembic.
revision = '1a7a18e7a5ad'
down_revision = '28e080284d0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('picture', sa.String(length=80), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('node_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_type_id'], [u'node_type.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_type_id', sa.Integer(), nullable=True),
    sa.Column('field_type', sa.String(length=128), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('name_url', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['node_type_id'], [u'node_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('custom_field_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['custom_field_id'], [u'custom_fields.id'], ),
    sa.ForeignKeyConstraint(['node_id'], [u'node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_properties')
    op.drop_table('custom_fields')
    op.drop_table('node')
    op.drop_table('node_type')
    ### end Alembic commands ###
